konveyor/tackle-test-generator-core

src/org/konveyor/tackle/testgen/core/DiffAssertionsGenerator.java, src/org/konveyor/tackle/testgen/model/JavaMethodModel.java
Use assertNull to handle assertions on null values.
Related to # (31)
=> Issue 31 assert null

pom.xml, test/data/irs/monolith/pom.xml
Updated library dependency versions flagged with vulnerability warnings
Tested locally with CI test cases
=> dependency version updates

src/org/konveyor/tackle/testgen/core/extender/TestSequenceExtender.java
Added error handling in extender for missing classpath dependencies and record the coverage status of the corresponding test plan rows.
Related to #30
Tested locally using CI test cases with missing library dependencies
=> extender missing dependency handling

src/org/konveyor/tackle/testgen/core/EvoSuiteTestGenerator.java
Added quotes to file system paths given as input to EvoSuite to support spaces
Related to # (34) in tackle-test-generator-cli repo
=> issue #34 add double quotes for file system paths to handle spaces

src/org/konveyor/tackle/testgen/core/AbstractJUnitTestImporter.java, src/org/konveyor/tackle/testgen/core/RandoopTestGenerator.java, src/org/konveyor/tackle/testgen/core/extender/ExtenderSummary.java, src/org/konveyor/tackle/testgen/core/extender/TestSequenceExtender.java, src/org/konveyor/tackle/testgen/util/Constants.java, test/java/org/konveyor/tackle/testgen/TestgenIntegrationTest.java, test/java/org/konveyor/tackle/testgen/core/extender/TestSequenceExtenderTest.java
Define a timeout on randoop generation process per class. If timeout is reached, delete test files generated for this class and move to next class.
Related to # (45)
=> Issue 45 randoop timeout

src/org/konveyor/tackle/testgen/core/extender/TestSequenceExtender.java, src/org/konveyor/tackle/testgen/util/Constants.java, test/java/org/konveyor/tackle/testgen/TestgenIntegrationTest.java, test/java/org/konveyor/tackle/testgen/core/extender/TestSequenceExtenderTest.java
Add app name to json coverage file name
=> Add app name to json coverage file name

src/org/konveyor/tackle/testgen/core/DiffAssertionsGenerator.java, src/org/konveyor/tackle/testgen/model/CTDTestPlanGenerator.java, src/org/konveyor/tackle/testgen/model/JavaMethodModel.java
recorded type to avoid compilation issues 2) handle negative infinity
value
Added casting on receiver objects to generated assertions to avoid compilation errors
Related to # (48)
=> issue #48 1) add to assertions casting of formal type to runtime

src/org/konveyor/tackle/testgen/util/Utils.java
Ignore empty lines in classpath file
Related to # (50) in tackle-test-generator-core repo
=> issue #50 ignore empty lines in the classpath file

src/org/konveyor/tackle/testgen/rta/RapidTypeAnalysis.java
class scene during iteration
Use a snapshot iterator in rapid type analysis to avoid failures on changes in class hierarchy that occur during iteration.
Related to # (51) in tackle-test-generator-cli repo
=> issue #51 use snapshot iterator to avoid failures due to changes in

src/org/konveyor/tackle/testgen/core/JUnitTestExporter.java, src/org/konveyor/tackle/testgen/core/extender/SequenceUtil.java, src/org/konveyor/tackle/testgen/core/extender/TestSequenceExtender.java, test/data/daytrader7/DayTrader_extended_sequences.json
Updated generation of test case names to contain the target method/constructor names in
the format `test_{method/constructor_name}_{int}`
Related to #38
Tested locally using CI tests and checking generated test method names
=> meaningful test case names

src/org/konveyor/tackle/testgen/core/DiffAssertionsGenerator.java, src/org/konveyor/tackle/testgen/core/executor/SequenceExecutor.java, test/java/org/konveyor/tackle/testgen/core/DiffAssertionGeneratorTest.java
Handled assertions of type byte, short and long using a suitable conversion of recorded values.
Related to # (53) in tackle-test-generator-cli repo
=> Issue 53 assertion type mismatch

src/org/konveyor/tackle/testgen/core/DiffAssertionsGenerator.java
Correct inner class names when casting in assertions
Related to # (17) in experiments repo
=> Issue 17 experiments compilation errors

src/org/konveyor/tackle/testgen/core/RandoopJUnitTestImporter.java
Bug fix - add new lines in Randoop filtered imported sequences.
=> Randoop seq import error

src/org/konveyor/tackle/testgen/core/DiffAssertionsGenerator.java, src/org/konveyor/tackle/testgen/core/executor/SequenceExecutor.java
void
Filter out potential getters when the method return type is void
Related to # (13) in experiments repo
=> issue #13 experiments repo - discard potential getters with return type

src/org/konveyor/tackle/testgen/core/JUnitTestExporter.java, src/org/konveyor/tackle/testgen/core/SequenceParser.java, src/org/konveyor/tackle/testgen/core/executor/SequenceExecutor.java, src/org/konveyor/tackle/testgen/core/extender/ExtenderSummary.java, src/org/konveyor/tackle/testgen/core/extender/SequencePool.java, src/org/konveyor/tackle/testgen/core/extender/TestSequenceExtender.java, src/org/konveyor/tackle/testgen/util/Constants.java, test/java/org/konveyor/tackle/testgen/TestUtils.java, test/java/org/konveyor/tackle/testgen/core/extender/TestSequenceExtenderTest.java
Implementation of parsing improvements: sequences with try statements, constructor calls as method arguments,
type parameters for map types and methods.
Added capability for partial parsing in cases where errors occur. 
Related to #56 
Tested locally using CI tests and apps; tested manually using additional test apps
=> Issue56 test parsing improvement

src/org/konveyor/tackle/testgen/core/DiffAssertionsGenerator.java
Bug fix in identifying null values for assertion generation
Related to # (17) experiments repo
=> issue #17 experiments repo - bug fix in identifying null value

src/org/konveyor/tackle/testgen/model/JavaMethodModel.java
model
filter out non-public types from the CTD model to avoid non-compilable tests
Related to # (17) in experiments repo
=> issue #17 experiments repo - filter out non-public types from the CTD

src/org/konveyor/tackle/testgen/core/extender/TestSequenceExtender.java
junit tests
Avoid importing non-public classes in final JUnit test cases
Related to # (17) in experiments repo
=> issue #17 experiments repo - avoid importing non-public classes in final

src/org/konveyor/tackle/testgen/core/DiffAssertionsGenerator.java
values
handle carriage return in asserted string values
Related to # (17) in experiments repo
=> issue #17 experiments repo - handle carriage return in asserted string

src/org/konveyor/tackle/testgen/model/CTDTestPlanGenerator.java, src/org/konveyor/tackle/testgen/util/Constants.java
designated file
CTD modeling outputs all non-targeted methods and their visibility to a designated file `<app_name>_ctd_non_targeted_methods.json`
Related to # (21) in experiments repo
=> issue #21 CTD modeling outputs all methods that it doesn't target to a

src/org/konveyor/tackle/testgen/core/extender/TestSequenceExtender.java
This PR contains updates to the test sequence extender to handle enum type parameters for target methods
Tested locally using CI test cases and an additional app containing enum type parameter
=> enum parameter types for target methods (#69)

src/org/konveyor/tackle/testgen/core/RandoopTestGenerator.java, src/org/konveyor/tackle/testgen/core/TestSequenceInitializer.java, src/org/konveyor/tackle/testgen/core/extender/ConstructorSequenceGenerator.java, src/org/konveyor/tackle/testgen/core/extender/SequenceUtil.java, test/java/org/konveyor/tackle/testgen/TestgenIntegrationTest.java, test/java/org/konveyor/tackle/testgen/core/RandoopTestGeneratorTest.java, test/java/org/konveyor/tackle/testgen/core/TestSequenceInitializerTest.java
Shorten evosuite command by targeting classes only instead of all individual methods
Related to # (60) in tackle-test-generator-cli repo
=> Issue 60 long command

src/org/konveyor/tackle/testgen/core/extender/ConstructorSequenceGenerator.java
Fix in constructor sequence generation on iterating over subtypes
=> Contructor sequnce fix

src/org/konveyor/tackle/testgen/core/DiffAssertionsGenerator.java
to Randoop API rounding issues
Refine delta in float and double assertions due to Randoop API rounding issues.
Related to # (58) in tackle-test-generator-cli repo
=> issue #58 tackle cli repo - refine delta in float/double assertions due

src/org/konveyor/tackle/testgen/core/JUnitTestExporter.java, src/org/konveyor/tackle/testgen/core/TestSequenceInitializer.java, src/org/konveyor/tackle/testgen/core/extender/ConstructorSequenceGenerator.java, src/org/konveyor/tackle/testgen/core/extender/TestSequenceExtender.java, src/org/konveyor/tackle/testgen/model/CTDModeler.java, src/org/konveyor/tackle/testgen/model/JavaMethodModel.java, src/org/konveyor/tackle/testgen/model/TypeAnalysisResults.java, src/org/konveyor/tackle/testgen/util/Constants.java
Test cases are created in the same package as the class they are testing. This also allows including in the CTD model non-private parameter types from the same package as the class under test, as well as protected types that the class under test inherits from.
Related to # (77)
=> Issue 77 package level tests

src/org/konveyor/tackle/testgen/model/CTDTestPlanGenerator.java
Avoid targeting anonymous classes
Related to # (27) in experiments repo
=> issue #27 experiments repo - don't target anonymous classes

src/org/konveyor/tackle/testgen/util/Constants.java
Updated nesting depth for constructor sequence generation to 3 (from unbounded depth)
=> constructor sequence generation with bounded nesting depth

src/org/konveyor/tackle/testgen/model/CTDModeler.java
Disabled acts (combinatorial testing tool) printouts.
Related to #28
=> Issue 28 disable acts prints

pom.xml, src/org/konveyor/tackle/testgen/classify/ClassifiedError.java, src/org/konveyor/tackle/testgen/classify/ClassifyErrors.java, src/org/konveyor/tackle/testgen/core/DiffAssertionsGenerator.java, src/org/konveyor/tackle/testgen/core/JUnitTestExporter.java, src/org/konveyor/tackle/testgen/core/SequenceParser.java, src/org/konveyor/tackle/testgen/core/TestSequenceInitializer.java, src/org/konveyor/tackle/testgen/core/executor/SequenceExecutor.java, src/org/konveyor/tackle/testgen/core/extender/ExtenderSummary.java, src/org/konveyor/tackle/testgen/core/extender/SequencePool.java, src/org/konveyor/tackle/testgen/core/extender/SequenceUtil.java, src/org/konveyor/tackle/testgen/core/extender/TestSequenceExtender.java, src/org/konveyor/tackle/testgen/model/CTDTestPlanGenerator.java, src/org/konveyor/tackle/testgen/model/ModelJsonConvertor.java, src/org/konveyor/tackle/testgen/model/RapidTypeAnalysis.java, src/org/konveyor/tackle/testgen/util/TackleTestJson.java, test/java/org/konveyor/tackle/testgen/classify/ClassificationTest.java, test/java/org/konveyor/tackle/testgen/core/BasicBlockSequenceParseTest.java, test/java/org/konveyor/tackle/testgen/core/DiffAssertionGeneratorTest.java, test/java/org/konveyor/tackle/testgen/core/TestSequenceInitializerTest.java, test/java/org/konveyor/tackle/testgen/core/executor/SequenceExecutorTest.java, test/java/org/konveyor/tackle/testgen/core/extender/TestSequenceExtenderTest.java, test/java/org/konveyor/tackle/testgen/model/CTDModelingTest.java, test/java/org/konveyor/tackle/testgen/model/RapidTypeAnalysisTest.java
Replace old Java json package with a newer more scalable and convenient package 
Related to # (24) in experiments repo
=> Issue 24 experiments json package

src/org/konveyor/tackle/testgen/core/extender/ConstructorSequenceGenerator.java, src/org/konveyor/tackle/testgen/core/extender/JavaCollectionTypes.java, src/org/konveyor/tackle/testgen/core/extender/TestSequenceExtender.java
Fix in handling of user-defined collection types that occur as parameters
of target methods/constructors or are needed for constructor sequence
generation.
- [x ] I have commented my code, particularly in hard-to-understand areas
=> Handling of user-defined collection types

pom.xml
Tagged systemPath dependencies as optional (they need not be pulled in case of transitive dependencies; e.g., for the cli lib download)
=> pom dependency update

.github/workflows/maven_build.yml
Updated workflow step for publishing jar to specify the unit module pom
=> workflow update for publishing jar

tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/CrawljaxRunner.java, tackle-test-generator-ui/test/data/petclinic/tkltest_ui_config.toml
This PR contains:
- Updates for simplifying the output directory structure created by crawljax
- Handling of unknown types for enum configuration options (e.g., browser, state assertion types)
=> Tkltest UI crawljax runner updates

tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/CrawljaxRunner.java
Updated crawljax runner to set the visual data option for frggen state abstraction to true
=> Crawljax visual data option for state abstraction

.github/workflows/ui_testgen_ci.yml, tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/CrawljaxRunner.java, tackle-test-generator-ui/test/data/sample/tkltest_ui_clickables_config.toml, tackle-test-generator-ui/test/data/sample/tkltest_ui_config.toml, tackle-test-generator-ui/test/java/org/konveyor/tackletest/ui/crawljax/CrawljaxRunnerTest.java
This PR contains updates to handling of clickables spec:
- Processing of click spec refinement based on text, xpath, and attributes
- Disabled children_of modifier for dont_click spec
- Updated test data and new test case for clickables spec processing
Tested using existing CI tests and newly added test case
=> Tkltest UI clickables spec updates

tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/CrawljaxRunner.java, tackle-test-generator-ui/test/data/addressbook/tkltest_ui_config.toml, tackle-test-generator-ui/test/data/petclinic/tkltest_ui_config.toml, tackle-test-generator-ui/test/data/sample/tkltest_ui_config.toml, tackle-test-generator-ui/test/java/org/konveyor/tackletest/ui/crawljax/CrawljaxRunnerTest.java
configurable
Make the number of time to explore a discovered action configurable 
Related to # (88) in planning repo
=> issue #88 planning repo - make  max number of action explorations

tackle-test-generator-unit/src/org/konveyor/tackle/testgen/model/JavaMethodModel.java
Soot was unable to process
Soot is unable to process some classes and marks them at dangling level. Trying to perform class hierarchy analysis on these classes will result in exception, hence we avoid analyzing these classes
Related to # (95) in planning repo
=> Skip class hierarchy analysis for classes that

tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/CrawljaxRunner.java
Patch for adding test generator plugin with correct assertion generation option
=> Fix plugin confguration for crawljax

tackle-test-generator-ui/test/data/addressbook/tkltest_ui_config_nonfrag.toml, tackle-test-generator-ui/test/data/petclinic/tkltest_ui_config_nonfrag.toml, tackle-test-generator-ui/test/java/org/konveyor/tackletest/ui/crawljax/CrawljaxRunnerTest.java
This PR contains test cases for non-fraggen mode of crawling (using petclinic and addressbook apps)
=> Tests cases for non-frag-mode crawling

tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/ConstructorSequenceGenerator.java
Handle the case of a non-parameterized map, e.g., java.util.Properties
Related to # (129) in planning repo
=> bug fix: handle the case of a non-parameterized map

tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/DiffAssertionsGenerator.java, tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/ConstructorSequenceGenerator.java, tackle-test-generator-unit/src/org/konveyor/tackle/testgen/model/JavaMethodModel.java, tackle-test-generator-unit/src/org/konveyor/tackle/testgen/util/Constants.java
Adjust deduced parameter types when they have a lower and upper range
=> Support parameterized types of range

tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/CrawljaxRunner.java
Add a clear error message for the case a user forgot to specify before_click
- [] Documentation update
=> UI config clear error message

tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/CrawljaxRunner.java
Fixed processing of `browser_pixel_density` option
=> Fixed handling of browser_pixel_density option

tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/CrawljaxRunner.java, tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/TackleTestBrowserProvider.java
This PR adds the implementation of browser provider class that creates Chrome instances with option for ignoring certificate errors.
=> Browser provisioning with certificate error option

tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/TackleTestBrowserProvider.java, tackle-test-generator-ui/src/org/konveyor/tackletest/ui/util/DriverProvider.java
This PR contains updates to browser provider to use web driver manager for provisioning chrome driver instances
=> Use webdriver manager to provision browser

tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/CrawljaxRunner.java
Add support for unlimited crawl depth
=> Add support for unlimited crawl depth

.github/workflows/ui_testgen_ci.yml, tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/plugins/TackleTestOnUrlFirstLoadPlugin.java, tackle-test-generator-ui/test/data/petclinic/tkltest_ui_precrawl_actions_config.toml
This PR adds support for reading input values for pre-crawl actions from environment variables.
=> Pre-crawl action input value from environment variable

tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/plugins/TackleTestOnUrlFirstLoadPlugin.java
Add an alert accept precrawl action
Related to # (161) in planning repo
=> Add alert accept precrawl action

tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/CrawljaxRunner.java, tackle-test-generator-ui/test/java/org/konveyor/tackletest/ui/crawljax/CrawljaxRunnerTest.java
Add support for specifying don't click on children of
Related to # (163) in planning repo
=> Add support for specifying dont click on children of

README.md
=> Add a link to Konveyor CoC

README.md, tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/CrawljaxRunner.java, tackle-test-generator-ui/test/java/org/konveyor/tackletest/ui/crawljax/CrawljaxRunnerTest.java, tackle-test-generator-unit/pom.xml, tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/SequenceParser.java
Fix faster xml jackson vulnerability (dependable bot PR is not working)
=> Fix faster xml jackson vulnerability

tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/TestSequenceExtender.java, tackle-test-generator-unit/src/org/konveyor/tackle/testgen/model/JavaMethodModel.java, tackle-test-generator-unit/src/org/konveyor/tackle/testgen/model/RapidTypeAnalysis.java
handling uncouth exceptions
Please include a summary of the change and the issue that the PR is related to.
Please also include relevant motivation and context.
List any dependencies that are required for this change.
Related to # 172
=> Skip unresolved exceptions

tackle-test-generator-ui/pom.xml, tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/plugins/TackleTestOnUrlFirstLoadPlugin.java, tackle-test-generator-ui/test/data/sample/tkltest_ui_precrawl_actions_config.toml, tackle-test-generator-ui/test/java/org/konveyor/tackletest/ui/crawljax/CrawljaxRunnerTest.java
Pre-crawl action that supports TOTP generation and submission.
=> Precrawl action for TOTP submission

tackle-test-generator-unit/src/org/konveyor/tackle/testgen/model/CTDTestPlanGenerator.java
Signed-off-by: rachelt44 <rachelt@il.ibm.com>
Remove single quotes wrapping of included and excluded classes list in case it was added to avoid misinterpretation of special characters in command line (e.g., $ sign)
Related to # (175) planning repo
=> Handle single quotes wrapping of included and excluded classes list

tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/JUnitTestExporter.java, tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/JavaCollectionTypes.java
Avoid compilation issues by correctly handling parameterized methods during unit test export, and correctly handling parameterized type parameters containing variables during sequence extension. Nested parameterized type parameters are currently still not handled.
Related to # (177) in planning repo
=> Fix for parameterized methods and parameterized types containing variables 

tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/ConstructorSequenceGenerator.java, tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/SequencePool.java, tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/SequenceUtil.java, tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/extender/TestSequenceExtender.java
Please include a summary of the change and the issue that the PR is related to.
Please also include relevant motivation and context.
List any dependencies that are required for this change.
Related to # (177) in planning repo
=> Support casting to parameterized type parameters in method calls during sequence extender

tackle-test-generator-ui/pom.xml
Updated crawljax dependency to a patched commit (for crawl overview failure); added dependency management for resolving jackson version.
=> Patch for crawljax dependency

tackle-test-generator-ui/pom.xml, tackle-test-generator-ui/src/org/konveyor/tackletest/ui/crawljax/TackleTestBrowserProvider.java
Crawljax upgrade to version 5.2.1. Fix in browser provider to handle chromedrive 111 issue. 
=> Crawljax version upgrade and chromedriver fix

tackle-test-generator-unit/src/org/konveyor/tackle/testgen/core/TestSequenceInitializer.java
Updated test sequence initializer to ignore errors about tests not generated.
=> Test sequence initializer error update
